### ISSUE TITLE
How to modify font-size for different devices

### ISSUE THREAD

**Issue by jsmm** [wxxedu/obsidianki4#6]
Hi. The font-size in Obsidianki's template is far too small for me when rendered by Ankimobile both in iPad and iPhone. I seem incapable of modifying this setting in css for the mobile apps, unlike with Anki's native templates. Could you please provide help on what is the setting in Obsidianki's template to be modified?
And thanks so much for this useful add-on.

**Comment by jsmm** [comment]
I have replaced the css of Obsidianki's template with Anki's native cloze css. And I have applied [Auto Markdown - fix version](https://ankiweb.net/shared/info/15061497). It seems to me that now my files are rendering well. As far as I can tell, I'm not missing any of Obsidianki's features, or am I?

**Comment by wxxedu** [comment]
Hi! I haven’t tried obsidianki out on other platforms. I will take a look at it and try getting this problem resolved.

**Comment by wxxedu** [comment]
I removed the CSS layer, and I think that it looks okay for now. 
[Obsidianki.4.apkg.zip](https://github.com/wxxedu/obsidianki4/files/5876305/Obsidianki.4.apkg.zip)

**Comment by wxxedu** [comment]
You can now add any custom CSS in this template.

**Comment by jsmm** [comment]
Thanks for your attention! 

Keeping the styling for highlights is good. As for fonts, I think Apple's iOS doesn't allow `@import`. And PingFang SC is not among Apple's [preinstalled fonts](https://developer.apple.com/fonts/system-fonts/).

**Comment by jantmm** [comment]
Setting [Platform-Specific CSS](https://docs.ankiweb.net/#/templates/styling?id=platform-specific-css) is what renders fonts appropriately in my different devices:

```
.card {
  text-align: left;
  background-color: white;
	font-family: Helvetica, Arial;
}

.cloze {
 font-weight: bold;
 color: orange;
}

.nightMode .cloze {
 color: lightblue;
}

.mac .card {
	font-size: 20px;
}

.win .card {
	font-size: 20px;
}

.linux .card {
	font-size: 20px;
}

.iphone .card {
  font-size: 22px;
}

.ipad .card {
  font-size: 10px;
}

```

**Comment by jsmm** [comment]
Setting [Platform-Specific CSS](https://docs.ankiweb.net/#/templates/styling?id=platform-specific-css) is what has finally rendered fonts appropriately in the different Apple devices I use. As far as I am concerned, this issue is closed. Thanks again for your reply.

```
.card {
  text-align: left;
  background-color: white;
	font-family: Helvetica, Arial;
}

.cloze {
 font-weight: bold;
 color: orange;
}

.nightMode .cloze {
 color: lightblue;
}

.mac .card {
	font-size: 20px;
}

.win .card {
	font-size: 20px;
}

.linux .card {
	font-size: 20px;
}

.iphone .card {
  font-size: 22px;
}

.ipad .card {
  font-size: 10px;
}

```

**Comment by wxxedu** [comment]
Hi! Thanks!
As I don't personally plan to use this CSS, I may not change it in my file. You can download the latest apkg for the template (I fixed a little problems) and paste the css into it. Sorry for the inconvenience, and thanks a lot!
